### ISSUE TITLE
Static HUD math has issues

### ISSUE THREAD

**Issue by apoapostolov** [illandril/FoundryVTT-token-hud-scale#21]
When you zoom out, the Static HUD seems to increase the size more than the decrease of the zoom ratio, causing it to bloat slightly the further you zoom out.

**Comment by illandril** [comment]
I don't see this, and I think you're just thinking it increases due to an optical illusion. It definitely feels like it gets bigger when you zoom out, but if you take a screenshot at each zoom level and compare them directly they're the same size.

![scale2](https://user-images.githubusercontent.com/469205/119003673-e9c38700-b95b-11eb-9ab2-d668e8d29794.gif)

![scale](https://user-images.githubusercontent.com/469205/119001619-21c9ca80-b95a-11eb-9821-058dd820a9d7.gif)

There is some slight shifting by up to 1px here and there, but that is due to subpixel rendering and is unavoidable (unless you could manage to zoom in and out so that the token was exactly centered on a pixel... which I can't manage to do at any scale no matter how hard I try - the HUD is always shifted by a fraction of a pixel). You'll have the same shifts by leaving the scale unchanged and just panning the canvas around. In my gif above, the last 3 frames are all changing the zoom by just one step each time, and the HUD shifts just as much as the shift between the first frame and last frame (which goes from one extreme to the other in zoom).

If it's not just an optical illusion for you and/or those slight shifts due to subpixel rendering, and you are actually seeing more than a 1px difference between the max and min zoom for the HUD when using Static scaling, let me know what browser and OS you're using (including the version) and I can look into it more.
