### ISSUE TITLE
Notification message keeps showing up, can be annoying

### ISSUE THREAD

**Issue by apoapostolov** [illandril/FoundryVTT-token-hud-scale#22]
This message is endlessly showing for me with each load of Foundry. Is there a way to stop it?

![image](https://user-images.githubusercontent.com/4083812/119251963-02c57580-bbb2-11eb-82b7-5e1e3328d370.png)

**Comment by illandril** [comment]
That message should show at most once per world when that world first gets version 1.3.0 or newer. Even if you remove the module and re-add it later, it shouldn't show again for that world.
If you're seeing it more often, either something is causing your Foundry to lose world-level settings (in which case any other settings you set might be getting lost as well), or some other module is incorrectly setting the "settingsVersion" setting for this module instead of setting their own module's settings.

What system are you using, what other modules, and what are the versions for Foundry, the system, and your modules?

**Comment by illandril** [comment]
I suspect the cause for this is an issue with some hook timing changes in 0.8.x - this should stop happening in v1.4 (which will be for Foundry 0.8.5+ only).
