### ISSUE TITLE
Dynamic HUD Scaler math seems off - doesn't maintain ratio

### ISSUE THREAD

**Issue by apoapostolov** [illandril/FoundryVTT-token-hud-scale#24]
The static HUD scalability seems to not follow zoom ratio, and generates problems at minimum and maximum zoom

![image](https://user-images.githubusercontent.com/4083812/124033328-802aa400-da02-11eb-9529-0d6899ccafbd.png)
![image](https://user-images.githubusercontent.com/4083812/124033354-86208500-da02-11eb-9782-88fdfbe2a7bf.png)
![image](https://user-images.githubusercontent.com/4083812/124033396-8de02980-da02-11eb-853e-26fdbcaa83e8.png)

**Comment by illandril** [comment]
This sounds exactly like #21.

The scaling in your screenshots looks correct to me, with the only "issue" I see being the slight 1px shift (which is caused by the center of your viewport shifting by sub-pixel amounts, not due to the zooming, as I explained in #21).
![scale](https://user-images.githubusercontent.com/469205/124034424-2d80c600-d9c9-11eb-8d30-e0067e9e9048.gif)

**Comment by illandril** [comment]
I'm taking silence to mean "you are correct, and it is just an optical illusion - everything is working correctly".

**Comment by BronzeToad** [comment]
I was about to submit an issue for the same thing, but perhaps I'm expecting behavior that is not intended. I wouldn't expect the padding between the HUD and token to increase as you zoom out - is that intentional  behavior?

![Screen Shot 2021-09-12 at 11 16 35 PM](https://user-images.githubusercontent.com/45736019/133198866-39393117-fa02-4722-a7a7-c9b3840185d6.png)

**Comment by illandril** [comment]
Yes, that is intentional.

If the padding between the token and the hud did not increase with static HUD scaling, then the hud would quickly start to overlap itself when you zoomed out (like it already does in some cases for smaller tokens if you have modules or systems that add elements to the Token HUD).
![overlap](https://user-images.githubusercontent.com/469205/133270799-e7d5231c-94d2-4203-b488-4da3bc2da2f0.png)

If you look at apoapostolov's screenshots, you'd have much, much worse overlap when zooming out if the padding decreased without also completely rearranging things.

I could theoretically recalculate the positioning of everything in the HUD to get it closer to the token, but doing that would be an excessive amount of work for minimal gain (even with the simple "D&D 5e System only, no other modules that touch the Token HUD" case... throw in the many different ways other modules and systems tweak the Token HUD and it gets way worse).

**Comment by BronzeToad** [comment]
That makes perfect sense. Thanks for the info and thank you for the hard work. This module is on my short list when I give new GMs on foundry my must-have modules.
