### ISSUE TITLE
Option to set different numbers of effect Icons per row/column based on token size

### ISSUE THREAD

**Issue by MrPotatoZed** [illandril/FoundryVTT-token-hud-scale#30]
Being able to set the number/size of the effect icons is great but the sizes differ significantly based on the token size. 3 icons per column/row looks good on size medium (1x1) and smaller tokens but 3 icons look relatively huge on a size large (2x2)or bigger token and end up covering more of our pretty bbeg tokens than is necessary to show the effects. If it's not too much trouble, being able to set it so that we could have 3 icons for size M, 4 for size L, 5 for size H, and 6 for size G (or whatever number folks preferred) would be pretty awesome. 

Thanks for your work on this excellent mod.

**Comment by illandril** [comment]
Instead of having separate icon sizes by token size, I made the tokens scale based on grid size instead of token size, so they are consistent no matter what size the token is (unless the token is smaller than 1x1, in which case they might be a little smaller due to rounding issues).
I'm hoping that works as well, if not better, than having separate scale settings for different token sizes.

**Comment by MrPotatoZed** [comment]
That's a much better solution and it looks great. Thank you!
