### ISSUE TITLE
Large tokens make the UI way out of position

### ISSUE THREAD

**Issue by Zamrod** [illandril/FoundryVTT-token-hud-scale#35]
While experimenting with extremely large tokens for Spelljamming ships, the scaler causes the HUD to be way out of position and most of it to be off screen entirely:

![image](https://user-images.githubusercontent.com/12570777/184174507-703c7e79-9c20-4eed-a4dd-4a49cd650475.png)

**Comment by Zamrod** [comment]
That is the size I would like the HUD to be, but it is just in the wrong spot

**Comment by Zamrod** [comment]
Here's a better picture of where the UI ends up
![image](https://user-images.githubusercontent.com/12570777/184175490-d66e622f-1ad0-4118-9874-5b55b0d2fda1.png)

**Comment by illandril** [comment]
Can you provide me with the specific settings you are using for both the token (specifically the "Appearance" tab) and for the Token Hud Scaler module? (screenshots of those two settings windows are fine)

Also, please answer these questions...

**Foundry Versions**
 - Version of this module:
 - Foundry Version:
 - System Name and Version:
 - Browser Name and Version:

**What other modules did you have active when experiencing this issue (include both names and versions)?**
Tidy UI Game Settings (NOT Illandril's Tidy Module Settings) provides an Export option that makes getting this list easy.

**Comment by Zamrod** [comment]
> Can you provide me with the specific settings you are using for both the token (specifically the "Appearance" tab) and for the Token Hud Scaler module? (screenshots of those two settings windows are fine)
> 
![image](https://user-images.githubusercontent.com/12570777/184196870-b3078066-0e8a-4dac-b48b-10ff67fde222.png)

![image](https://user-images.githubusercontent.com/12570777/184196996-21234f79-6470-4705-8b4a-16ac7795eff1.png)

> Also, please answer these questions...
> 
> **Foundry Versions**
> 
> * Version of this module:

![image](https://user-images.githubusercontent.com/12570777/184197161-8361c466-761e-4272-bef7-3945607de19e.png)

> * Foundry Version:
> * System Name and Version:

![image](https://user-images.githubusercontent.com/12570777/184197071-d8643a61-68ae-4607-845c-44e92387cda1.png)

> * Browser Name and Version:

Tried in both Chrome (Version 104.0.5112.81 (Official Build) (64-bit)) and Edge (Version 104.0.1293.47 (Official build) (64-bit))

> 
> **What other modules did you have active when experiencing this issue (include both names and versions)?** Tidy UI Game Settings (NOT Illandril's Tidy Module Settings) provides an Export option that makes getting this list easy.

I took the screenshot with other modules enabled but I disabled them all and attempted it again with the same effect. So other modules are not affecting the behavior.

**Comment by illandril** [comment]
I still want to know what other modules you were using that were changing what ends up in the HUD, to make sure any change I make doesn't break those modules.

The way the HUD works is there are three columns, with the middle column taking up the same width as the token.
The middle column is split into three rows, with the middle row taking up the same height as the token.
This layout of the HUD and this "Token Size" spacing are all part of Foundry itself.

You are experiencing two separate issues...
1. The HUD isn't centered on the token (a bug in my HUD position adjustment logic in some scenarios)
2. The HUD spacing being based on the token size isn't natural or desirable when the HUD doesn't scale based on the scale of the token (for smaller tokens, this strange spacing isn't a big deal, because it's still reasonably close... but as the token gets larger, that difference in spacing becomes more and more obvious)

Fixing issue 1 should be fairly trivial, but fixing just that would actually make things worse for you (because the first resource bar, which you're using for health, would also be really far from the token... though the second resource bar, which would currently off the screen for you if you had it on, would be close enough to actually be visible).
Fixing issue 2 will be trickier because lots of other modules mess with the contents of the HUD. If I change how big the HUD is relative to the token, that could break those other modules if any of them were positioning content based on the default HUD sizing logic.

**Comment by Zamrod** [comment]
[moduleList.txt](https://github.com/illandril/FoundryVTT-token-hud-scale/files/9311604/moduleList.txt)
Here's my module list renamed from .json to .txt

I think most of the UI that was added was from:
Show Art
Drag Ruler
DF's Quality of Life
Light's HUD+ATE
Argon Combat HUD

Though not listed there that I sometimes use is:
Token Variant Art

**Comment by illandril** [comment]
Thanks. I might have enough time to work on a fix this weekend (but no promises).

**Comment by illandril** [comment]
Note: This issue is fixed in the version of Illandril's Token HUD Scaler that supports v10 of FoundryVTT.
I recommend waiting until v10 is released, and all the modules you use have been updated to support v10 before updating.
