### ISSUE TITLE
Conflict with Token Auras module

### ISSUE THREAD

**Issue by CepheiA2** [illandril/FoundryVTT-token-hud-scale#38]
**Describe the bug**
Double the status effect when Token Auras is active.

**What steps did you take before experiencing the problem?**
Have both modules active

**What did you expect to happen?**
One of the module disable the other one

**What happened instead?**
both apply the icon

**Screenshots**
![image](https://user-images.githubusercontent.com/85868381/195055604-5c54812d-e9c5-4d3f-ab5c-f259857d06c4.png)

**Foundry Versions**
 - Version of this module: 2.1.2
 - Foundry Version: V10
 - System Name and Version: DnD 5e, last update
 - Browser Name and Version: Chrome

**What other modules did you have active when experiencing this issue (include both names and versions)?**
Token Auras, 2.1
Combat Utility Belt

**Comment by illandril** [comment]
While I've stopped the one specific scenario that caused this bug to happen when Token Auras and Illandril's Token HUD Scale are both active, what is actually causing the double-draw is an issue in PIXI and/or how Foundry is using PIXI (I didn't dig into the details, so I don't know specifically where the issue is... but neither my module nor Token Auras are directly drawing anything - I reposition PIXI elements, and Token Auras just calls Foundry's existing draw function and creates additional, unrelated PIXI elements), so there may very well be more situations that cause the same issue.
